DROP TABLE podcasts;
CREATE TABLE IF NOT EXISTS podcasts (podcast_episode_id serial PRIMARY KEY, podcast_title TEXT, episode_title TEXT, published_date TEXT,authors TEXT, language VARCHAR(16), description TEXT, keywords TEXT, episode_url TEXT, cache_url TEXT, cache_file TEXT, transcript_file TEXT, duration REAL, type VARCHAR(64), episode_json JSON);

CREATE INDEX IF NOT EXISTS episode_url_index on podcasts (episode_url);
CREATE INDEX IF NOT EXISTS cache_url_index on podcasts (cache_url);
CREATE INDEX IF NOT EXISTS cache_file_index on podcasts (cache_file);
